// lib/links.ts
// ============================================================
// JARVIS - 73 Curated Free AI Tools
// Philosophy: Quality > Quantity. These 73 are the BEST free tools.
// Add more via GitHub Issues → weekly review → approved → auto-added
// ============================================================

export interface AILink {
  id: string;
  name: string;
  url: string;
  category: string;
  description: string;
  icon: string;           // emoji
  color: string;          // hex color for card
  freeType: 'free' | 'freemium' | 'limited' | 'credits';
  tags: string[
  // ─────────────────────────────────────────────
  // 🎙️ AI VOICE & PODCAST
  // ─────────────────────────────────────────────
  {
    id: 'voice-001',
    name: 'Murf AI',
    url: 'https://murf.ai',
    category: 'audio',
    description: 'AI voiceover studio - free plan 10 min',
    icon: '🎙️',
    color: '#7c3aed',
    freeType: 'limited',
    tags: ['voice', 'voiceover', 'tts', 'murf', 'studio'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'voice-002',
    name: 'Play.ht',
    url: 'https://play.ht',
    category: 'audio',
    description: 'AI text to speech 900+ voices - free plan',
    icon: '▶️',
    color: '#3b82f6',
    freeType: 'freemium',
    tags: ['voice', 'tts', 'speech', 'play.ht', 'voices'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'social-001',
    name: 'Predis AI',
    url: 'https://predis.ai',
    category: 'writing',
    description: 'AI social media post generator - free plan',
    icon: '📱',
    color: '#ec4899',
    freeType: 'freemium',
    tags: ['social', 'instagram', 'post', 'predis', 'content'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'social-002',
    name: 'Tweet Hunter',
    url: 'https://tweethunter.io',
    category: 'writing',
    description: 'AI Twitter/X growth tool - free trial',
    icon: '🐦',
    color: '#1da1f2',
    freeType: 'limited',
    tags: ['social', 'twitter', 'tweet', 'growth', 'AI'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'ecom-001',
    name: 'Flair AI',
    url: 'https://flair.ai',
    category: 'image',
    description: 'AI product photography - free credits',
    icon: '📦',
    color: '#f97316',
    freeType: 'credits',
    tags: ['ecommerce', 'product', 'photo', 'flair', 'shoot'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'dev-001',
    name: 'Continue.dev',
    url: 'https://continue.dev',
    category: 'code',
    description: 'Open source AI code assistant - free forever',
    icon: '🔧',
    color: '#7c3aed',
    freeType: 'free',
    tags: ['code', 'open source', 'continue', 'IDE', 'free'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'dev-002',
    name: 'Warp Terminal',
    url: 'https://warp.dev',
    category: 'code',
    description: 'AI-powered terminal - free for personal use',
    icon: '⌨️',
    color: '#18181b',
    freeType: 'free',
    tags: ['code', 'terminal', 'warp', 'AI', 'command line'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'trans-001',
    name: 'DeepL',
    url: 'https://deepl.com',
    category: 'writing',
    description: 'Best AI translation tool - free plan',
    icon: '🌍',
    color: '#0f2b46',
    freeType: 'freemium',
    tags: ['translation', 'deepl', 'language', 'free', 'translate'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'trans-002',
    name: 'Google Translate',
    url: 'https://translate.google.com',
    category: 'writing',
    description: 'Google AI translation - completely free',
    icon: '🔤',
    color: '#4285f4',
    freeType: 'free',
    tags: ['translation', 'google', 'language', 'free', 'translate'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'trend-006',
    name: 'Grok',
    url: 'https://grok.com',
    category: 'chat',
    description: 'xAI Grok - real-time AI with X/Twitter data',
    icon: '🤖',
    color: '#18181b',
    freeType: 'freemium',
    tags: ['chat', 'grok', 'xai', 'twitter', 'realtime'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'trend-007',
    name: 'DeepSeek',
    url: 'https://chat.deepseek.com',
    category: 'chat',
    description: 'DeepSeek R1 - powerful free reasoning AI',
    icon: '🐋',
    color: '#1e40af',
    freeType: 'free',
    tags: ['chat', 'deepseek', 'reasoning', 'free', 'R1'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'trend-008',
    name: 'Napkin AI',
    url: 'https://napkin.ai',
    category: 'productivity',
    description: 'Text to visual diagrams instantly - free',
    icon: '📐',
    color: '#f59e0b',
    freeType: 'free',
    tags: ['diagram', 'visual', 'chart', 'napkin', 'free'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'trend-009',
    name: 'Midjourney',
    url: 'https://midjourney.com',
    category: 'image',
    description: 'Best AI art generation - limited free via Discord',
    icon: '⛵',
    color: '#18181b',
    freeType: 'limited',
    tags: ['image', 'art', 'midjourney', 'discord', 'generate'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'trend-010',
    name: 'Luma Photon',
    url: 'https://lumalabs.ai/photon',
    category: 'image',
    description: 'Fast high-quality AI image generation - free credits',
    icon: '💡',
    color: '#7c3aed',
    freeType: 'credits',
    tags: ['image', 'generate', 'luma', 'photon', 'fast'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'trend-011',
    name: 'Google AI Studio',
    url: 'https://aistudio.google.com',
    category: 'code',
    description: 'Build with Gemini API - free playground',
    icon: '🔬',
    color: '#4285f4',
    freeType: 'free',
    tags: ['code', 'gemini', 'google', 'API', 'build'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'trend-012',
    name: 'Hugging Face Spaces',
    url: 'https://huggingface.co/spaces',
    category: 'productivity',
    description: '1000s of free AI demos and tools in one place',
    icon: '🤗',
    color: '#ff9d00',
    freeType: 'free',
    tags: ['AI', 'demos', 'tools', 'huggingface', 'free'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'trend-013',
    name: 'Claude Projects',
    url: 'https://claude.ai/projects',
    category: 'productivity',
    description: 'Organize AI workflows with knowledge - free plan',
    icon: '📁',
    color: '#cc785c',
    freeType: 'freemium',
    tags: ['productivity', 'claude', 'projects', 'knowledge', 'workflow'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'trend-014',
    name: 'Poe by Quora',
    url: 'https://poe.com',
    category: 'chat',
    description: 'Multiple AI models in one app - free plan',
    icon: '🎭',
    color: '#8b5cf6',
    freeType: 'freemium',
    tags: ['chat', 'poe', 'multiple models', 'quora', 'AI'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'trend-015',
    name: 'Perplexity Pages',
    url: 'https://perplexity.ai/pages',
    category: 'writing',
    description: 'AI-written articles with citations - free',
    icon: '📰',
    color: '#20b2aa',
    freeType: 'free',
    tags: ['writing', 'article', 'research', 'perplexity', 'pages'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'trend-016',
    name: 'Udio Music',
    url: 'https://udio.com',
    category: 'audio',
    description: 'Create full songs with AI vocals - free tier',
    icon: '🎵',
    color: '#7c3aed',
    freeType: 'limited',
    tags: ['audio', 'music', 'song', 'vocals', 'udio'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'trend-017',
    name: 'Gamma Slides',
    url: 'https://gamma.app',
    category: 'productivity',
    description: 'AI presentation in seconds - free plan',
    icon: '📊',
    color: '#7c3aed',
    freeType: 'freemium',
    tags: ['productivity', 'presentation', 'slides', 'gamma', 'AI'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'trend-018',
    name: 'Suno AI Songs',
    url: 'https://suno.com',
    category: 'audio',
    description: 'Generate complete songs from text - free',
    icon: '🎤',
    color: '#8b5cf6',
    freeType: 'freemium',
    tags: ['audio', 'music', 'song', 'generate', 'suno'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'trend-019',
    name: 'Dora AI',
    url: 'https://dora.run',
    category: 'design',
    description: 'AI 3D animated website builder - free credits',
    icon: '🌐',
    color: '#6366f1',
    freeType: 'credits',
    tags: ['design', 'website', '3d', 'animated', 'dora'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'trend-020',
    name: 'Jitter Video',
    url: 'https://jitter.video',
    category: 'design',
    description: 'AI motion design for UI - free plan',
    icon: '✨',
    color: '#f43f5e',
    freeType: 'freemium',
    tags: ['design', 'motion', 'animation', 'jitter', 'UI'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'trend-021',
    name: 'Mixo',
    url: 'https://mixo.io',
    category: 'productivity',
    description: 'AI startup website in seconds - free trial',
    icon: '🚀',
    color: '#10b981',
    freeType: 'limited',
    tags: ['website', 'startup', 'builder', 'mixo', 'AI'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'trend-022',
    name: 'Hotpot AI',
    url: 'https://hotpot.ai',
    category: 'image',
    description: 'AI tools for images, art, writing - free credits',
    icon: '🔥',
    color: '#f97316',
    freeType: 'credits',
    tags: ['image', 'art', 'writing', 'hotpot', 'tools'],
    isActive: true,
    addedAt: '2026-01-01',
  },
];
  isActive: boolean;
  addedAt: string;        // ISO date
}

export const AI_CATEGORIES = [
  { id: 'all',          name: 'All Tools',         icon: '🤖', color: '#ff1a88' },
  { id: 'image',        name: 'AI Image',           icon: '🎨', color: '#ff6b6b' },
  { id: 'video',        name: 'AI Video',           icon: '🎬', color: '#ffa500' },
  { id: 'writing',      name: 'AI Writing',         icon: '✍️',  color: '#4ecdc4' },
  { id: 'code',         name: 'AI Code',            icon: '💻', color: '#45b7d1' },
  { id: 'audio',        name: 'AI Audio',           icon: '🎵', color: '#96ceb4' },
  { id: 'chat',         name: 'AI Chat',            icon: '💬', color: '#9b59b6' },
  { id: 'design',       name: 'AI Design',          icon: '🎭', color: '#e74c3c' },
  { id: '3d',           name: 'AI 3D',              icon: '🧊', color: '#3498db' },
  { id: 'search',       name: 'AI Search',          icon: '🔍', color: '#2ecc71' },
  { id: 'productivity', name: 'Productivity',       icon: '⚡', color: '#f39c12' },
  { id: 'avatar',       name: 'AI Avatar',          icon: '👤', color: '#e056fd' },
] as const;

export const JARVIS_LINKS: AILink[] = [
  // ─────────────────────────────────────────────
  // 🎨 AI IMAGE GENERATION
  // ─────────────────────────────────────────────
  {
    id: 'img-001',
    name: 'Ideogram',
    url: 'https://ideogram.ai',
    category: 'image',
    description: 'Free AI image generation with text rendering',
    icon: '🎨',
    color: '#ff6b6b',
    freeType: 'free',
    tags: ['image', 'generate', 'text', 'logo', 'art'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'img-002',
    name: 'Adobe Firefly',
    url: 'https://firefly.adobe.com',
    category: 'image',
    description: 'Adobe AI image generation - free credits monthly',
    icon: '🔥',
    color: '#ff4500',
    freeType: 'credits',
    tags: ['image', 'generate', 'professional', 'adobe'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'img-003',
    name: 'Bing Image Creator',
    url: 'https://www.bing.com/images/create',
    category: 'image',
    description: 'Microsoft DALL-E 3 powered - completely free',
    icon: '🔷',
    color: '#0078d4',
    freeType: 'free',
    tags: ['image', 'generate', 'dalle', 'microsoft', 'free'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'img-004',
    name: 'Canva AI',
    url: 'https://www.canva.com/ai-image-generator',
    category: 'image',
    description: 'Canva free AI image generator',
    icon: '🎭',
    color: '#00c4cc',
    freeType: 'freemium',
    tags: ['image', 'generate', 'design', 'canva'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'img-005',
    name: 'Stable Diffusion (Clipdrop)',
    url: 'https://clipdrop.co/stable-diffusion',
    category: 'image',
    description: 'Stable Diffusion XL - free tier available',
    icon: '⚡',
    color: '#7c3aed',
    freeType: 'limited',
    tags: ['image', 'stable diffusion', 'generate', 'AI'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'img-006',
    name: 'Leonardo AI',
    url: 'https://leonardo.ai',
    category: 'image',
    description: 'Free daily tokens for AI image generation',
    icon: '🦁',
    color: '#f59e0b',
    freeType: 'credits',
    tags: ['image', 'generate', 'game', 'art', 'tokens'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'img-007',
    name: 'Playground AI',
    url: 'https://playground.com',
    category: 'image',
    description: '500 free images per day',
    icon: '🎮',
    color: '#ec4899',
    freeType: 'free',
    tags: ['image', 'generate', 'playground', 'free', 'daily'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'img-008',
    name: 'Upscayl',
    url: 'https://upscayl.org',
    category: 'image',
    description: 'Free open-source AI image upscaler',
    icon: '🔍',
    color: '#10b981',
    freeType: 'free',
    tags: ['image', 'upscale', 'enhance', 'free', 'open-source'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'img-009',
    name: 'Remove.bg',
    url: 'https://remove.bg',
    category: 'image',
    description: 'Remove background from images - free',
    icon: '✂️',
    color: '#6366f1',
    freeType: 'limited',
    tags: ['image', 'background', 'remove', 'cut'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'img-010',
    name: 'Pincel AI',
    url: 'https://pincel.app',
    category: 'image',
    description: 'AI photo editing - inpaint, outpaint, edit',
    icon: '🖌️',
    color: '#f97316',
    freeType: 'freemium',
    tags: ['image', 'edit', 'inpaint', 'outpaint', 'photo'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // 🎬 AI VIDEO GENERATION
  // ─────────────────────────────────────────────
  {
    id: 'vid-001',
    name: 'Kling AI',
    url: 'https://klingai.com',
    category: 'video',
    description: 'High quality AI video generation - free credits',
    icon: '🎬',
    color: '#dc2626',
    freeType: 'credits',
    tags: ['video', 'generate', 'AI', 'kling', 'motion'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'vid-002',
    name: 'Hailuo AI',
    url: 'https://hailuoai.video',
    category: 'video',
    description: 'Free AI video generation by MiniMax',
    icon: '🌊',
    color: '#2563eb',
    freeType: 'free',
    tags: ['video', 'generate', 'hailuo', 'minimax', 'free'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'vid-003',
    name: 'Luma Dream Machine',
    url: 'https://lumalabs.ai/dream-machine',
    category: 'video',
    description: 'Realistic AI video - free tier available',
    icon: '💫',
    color: '#7c3aed',
    freeType: 'limited',
    tags: ['video', 'generate', 'luma', 'realistic'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'vid-004',
    name: 'Pika Labs',
    url: 'https://pika.art',
    category: 'video',
    description: 'AI video creation from text/image - free credits',
    icon: '⚡',
    color: '#db2777',
    freeType: 'credits',
    tags: ['video', 'generate', 'pika', 'text-to-video'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'vid-005',
    name: 'CapCut AI',
    url: 'https://capcut.com',
    category: 'video',
    description: 'Free video editing with AI features',
    icon: '✂️',
    color: '#000000',
    freeType: 'free',
    tags: ['video', 'edit', 'capcut', 'free', 'mobile'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'vid-006',
    name: 'DomoAI',
    url: 'https://domoai.app',
    category: 'video',
    description: 'Animate any image or video with AI style',
    icon: '🎭',
    color: '#0891b2',
    freeType: 'limited',
    tags: ['video', 'animate', 'style', 'transform'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // 💬 AI CHAT & REASONING
  // ─────────────────────────────────────────────
  {
    id: 'chat-001',
    name: 'ChatGPT',
    url: 'https://chat.openai.com',
    category: 'chat',
    description: 'GPT-4o - free tier available',
    icon: '🤖',
    color: '#10a37f',
    freeType: 'freemium',
    tags: ['chat', 'gpt', 'openai', 'general', 'reasoning'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'chat-002',
    name: 'Claude (Anthropic)',
    url: 'https://claude.ai',
    category: 'chat',
    description: 'Claude 3.5 - best for writing & analysis',
    icon: '🧠',
    color: '#cc785c',
    freeType: 'freemium',
    tags: ['chat', 'claude', 'writing', 'analysis', 'reasoning'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'chat-003',
    name: 'Gemini',
    url: 'https://gemini.google.com',
    category: 'chat',
    description: 'Google Gemini - free, multimodal AI',
    icon: '✨',
    color: '#4285f4',
    freeType: 'free',
    tags: ['chat', 'gemini', 'google', 'multimodal', 'free'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'chat-004',
    name: 'Perplexity',
    url: 'https://perplexity.ai',
    category: 'chat',
    description: 'AI search with real-time web results',
    icon: '🔍',
    color: '#20b2aa',
    freeType: 'freemium',
    tags: ['chat', 'search', 'perplexity', 'web', 'research'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'chat-005',
    name: 'Mistral (Le Chat)',
    url: 'https://chat.mistral.ai',
    category: 'chat',
    description: 'Mistral AI - fast, free, European AI',
    icon: '💨',
    color: '#ff7000',
    freeType: 'free',
    tags: ['chat', 'mistral', 'fast', 'free', 'european'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'chat-006',
    name: 'Meta AI',
    url: 'https://meta.ai',
    category: 'chat',
    description: 'Meta Llama 3 - completely free',
    icon: '♾️',
    color: '#0668e1',
    freeType: 'free',
    tags: ['chat', 'meta', 'llama', 'free', 'facebook'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'chat-007',
    name: 'Copilot',
    url: 'https://copilot.microsoft.com',
    category: 'chat',
    description: 'Microsoft Copilot with DALL-E 3 - free',
    icon: '🪟',
    color: '#0078d4',
    freeType: 'free',
    tags: ['chat', 'microsoft', 'copilot', 'bing', 'free'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // ✍️ AI WRITING
  // ─────────────────────────────────────────────
  {
    id: 'write-001',
    name: 'Notion AI',
    url: 'https://notion.so',
    category: 'writing',
    description: 'AI writing in Notion workspace',
    icon: '📝',
    color: '#000000',
    freeType: 'limited',
    tags: ['writing', 'notion', 'docs', 'notes', 'AI'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'write-002',
    name: 'Grammarly',
    url: 'https://grammarly.com',
    category: 'writing',
    description: 'AI grammar and writing assistant - free',
    icon: '✅',
    color: '#15c39a',
    freeType: 'freemium',
    tags: ['writing', 'grammar', 'check', 'improve'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'write-003',
    name: 'QuillBot',
    url: 'https://quillbot.com',
    category: 'writing',
    description: 'AI paraphrasing and writing tool - free',
    icon: '🪶',
    color: '#2e7d32',
    freeType: 'freemium',
    tags: ['writing', 'paraphrase', 'summarize', 'rephrase'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'write-004',
    name: 'Copy.ai',
    url: 'https://copy.ai',
    category: 'writing',
    description: 'AI copywriting - free plan available',
    icon: '📋',
    color: '#6366f1',
    freeType: 'freemium',
    tags: ['writing', 'copy', 'marketing', 'ads', 'content'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'write-005',
    name: 'Rytr',
    url: 'https://rytr.me',
    category: 'writing',
    description: 'AI writer - 10K chars free/month',
    icon: '🖊️',
    color: '#7c3aed',
    freeType: 'limited',
    tags: ['writing', 'content', 'blog', 'email', 'free'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // 💻 AI CODE
  // ─────────────────────────────────────────────
  {
    id: 'code-001',
    name: 'GitHub Copilot',
    url: 'https://github.com/features/copilot',
    category: 'code',
    description: 'AI code completion - free for students',
    icon: '🐙',
    color: '#24292e',
    freeType: 'limited',
    tags: ['code', 'github', 'copilot', 'completion', 'IDE'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'code-002',
    name: 'Cursor',
    url: 'https://cursor.com',
    category: 'code',
    description: 'AI-first code editor - free tier',
    icon: '⌨️',
    color: '#000000',
    freeType: 'freemium',
    tags: ['code', 'editor', 'cursor', 'AI', 'IDE'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'code-003',
    name: 'Replit AI',
    url: 'https://replit.com',
    category: 'code',
    description: 'Online coding with AI assistant - free',
    icon: '🔄',
    color: '#f26207',
    freeType: 'freemium',
    tags: ['code', 'replit', 'online', 'run', 'deploy'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'code-004',
    name: 'Bolt.new',
    url: 'https://bolt.new',
    category: 'code',
    description: 'Full-stack app from prompt - free credits',
    icon: '⚡',
    color: '#7c3aed',
    freeType: 'credits',
    tags: ['code', 'fullstack', 'app', 'build', 'deploy'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'code-005',
    name: 'v0 by Vercel',
    url: 'https://v0.dev',
    category: 'code',
    description: 'Generate React UI from description - free credits',
    icon: '🎯',
    color: '#000000',
    freeType: 'credits',
    tags: ['code', 'ui', 'react', 'vercel', 'frontend'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'code-006',
    name: 'CodePen AI',
    url: 'https://codepen.io/ai',
    category: 'code',
    description: 'AI-powered HTML/CSS/JS playground',
    icon: '🖥️',
    color: '#47cf73',
    freeType: 'free',
    tags: ['code', 'html', 'css', 'js', 'playground'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // 🎵 AI AUDIO & MUSIC
  // ─────────────────────────────────────────────
  {
    id: 'audio-001',
    name: 'Suno AI',
    url: 'https://suno.com',
    category: 'audio',
    description: 'Create songs from text - free daily credits',
    icon: '🎵',
    color: '#8b5cf6',
    freeType: 'credits',
    tags: ['audio', 'music', 'song', 'generate', 'suno'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'audio-002',
    name: 'Udio',
    url: 'https://udio.com',
    category: 'audio',
    description: 'AI music generation - free tier',
    icon: '🎹',
    color: '#ec4899',
    freeType: 'limited',
    tags: ['audio', 'music', 'generate', 'udio'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'audio-003',
    name: 'ElevenLabs',
    url: 'https://elevenlabs.io',
    category: 'audio',
    description: 'AI voice cloning & TTS - free 10K chars/month',
    icon: '🎤',
    color: '#1a1a2e',
    freeType: 'limited',
    tags: ['audio', 'voice', 'tts', 'clone', 'speech'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'audio-004',
    name: 'Mubert',
    url: 'https://mubert.com',
    category: 'audio',
    description: 'AI background music generation - free',
    icon: '🎶',
    color: '#00bcd4',
    freeType: 'freemium',
    tags: ['audio', 'music', 'background', 'ambient'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'audio-005',
    name: 'Adobe Podcast',
    url: 'https://podcast.adobe.com',
    category: 'audio',
    description: 'AI audio enhancement for podcasts - free',
    icon: '🎙️',
    color: '#ff0000',
    freeType: 'free',
    tags: ['audio', 'podcast', 'enhance', 'adobe', 'noise'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // 🎭 AI DESIGN
  // ─────────────────────────────────────────────
  {
    id: 'design-001',
    name: 'Canva',
    url: 'https://canva.com',
    category: 'design',
    description: 'Design with AI tools - free plan',
    icon: '🎨',
    color: '#00c4cc',
    freeType: 'freemium',
    tags: ['design', 'canva', 'graphic', 'template', 'poster'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'design-002',
    name: 'Looka',
    url: 'https://looka.com',
    category: 'design',
    description: 'AI logo maker - design free, pay to download',
    icon: '🏷️',
    color: '#f59e0b',
    freeType: 'limited',
    tags: ['design', 'logo', 'brand', 'AI', 'maker'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'design-003',
    name: 'Figma AI',
    url: 'https://figma.com',
    category: 'design',
    description: 'Design with AI features - free plan',
    icon: '🖼️',
    color: '#f24e1e',
    freeType: 'freemium',
    tags: ['design', 'figma', 'ui', 'ux', 'prototype'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'design-004',
    name: 'Brandmark',
    url: 'https://brandmark.io',
    category: 'design',
    description: 'AI logo + brand identity generator',
    icon: '✨',
    color: '#6366f1',
    freeType: 'limited',
    tags: ['design', 'logo', 'brand', 'identity'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'design-005',
    name: 'Colormagic',
    url: 'https://colormagic.app',
    category: 'design',
    description: 'AI color palette generator - free',
    icon: '🎨',
    color: '#ff6b9d',
    freeType: 'free',
    tags: ['design', 'color', 'palette', 'brand', 'free'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // 🧊 AI 3D
  // ─────────────────────────────────────────────
  {
    id: '3d-001',
    name: 'Meshy AI',
    url: 'https://meshy.ai',
    category: '3d',
    description: 'Text/image to 3D model - free credits',
    icon: '🧊',
    color: '#3b82f6',
    freeType: 'credits',
    tags: ['3d', 'model', 'generate', 'mesh', 'game'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: '3d-002',
    name: 'Spline AI',
    url: 'https://spline.design',
    category: '3d',
    description: '3D design with AI - free plan',
    icon: '🌀',
    color: '#8b5cf6',
    freeType: 'freemium',
    tags: ['3d', 'design', 'interactive', 'web', 'spline'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: '3d-003',
    name: 'Luma Genie',
    url: 'https://lumalabs.ai/genie',
    category: '3d',
    description: 'Text to 3D model by Luma Labs - free',
    icon: '💎',
    color: '#7c3aed',
    freeType: 'free',
    tags: ['3d', 'text', 'model', 'luma', 'generate'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // 🔍 AI SEARCH & RESEARCH
  // ─────────────────────────────────────────────
  {
    id: 'search-001',
    name: 'Perplexity',
    url: 'https://perplexity.ai',
    category: 'search',
    description: 'AI-powered research with real-time web',
    icon: '🔍',
    color: '#20b2aa',
    freeType: 'freemium',
    tags: ['search', 'research', 'web', 'AI', 'perplexity'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'search-002',
    name: 'You.com',
    url: 'https://you.com',
    category: 'search',
    description: 'AI search engine - free',
    icon: '🌐',
    color: '#4f46e5',
    freeType: 'free',
    tags: ['search', 'web', 'AI', 'you.com'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'search-003',
    name: 'Consensus',
    url: 'https://consensus.app',
    category: 'search',
    description: 'AI research paper search - free',
    icon: '📚',
    color: '#059669',
    freeType: 'freemium',
    tags: ['search', 'research', 'papers', 'science', 'academic'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // ⚡ PRODUCTIVITY
  // ─────────────────────────────────────────────
  {
    id: 'prod-001',
    name: 'Gamma',
    url: 'https://gamma.app',
    category: 'productivity',
    description: 'AI presentation maker - free plan',
    icon: '📊',
    color: '#7c3aed',
    freeType: 'limited',
    tags: ['productivity', 'presentation', 'slides', 'AI', 'gamma'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'prod-002',
    name: 'Napkin AI',
    url: 'https://napkin.ai',
    category: 'productivity',
    description: 'Text to visual diagrams - free',
    icon: '📐',
    color: '#f59e0b',
    freeType: 'free',
    tags: ['productivity', 'diagram', 'visual', 'chart'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'prod-003',
    name: 'Otter.ai',
    url: 'https://otter.ai',
    category: 'productivity',
    description: 'AI meeting transcription - free plan',
    icon: '🦦',
    color: '#0ea5e9',
    freeType: 'limited',
    tags: ['productivity', 'transcription', 'meeting', 'notes'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'prod-004',
    name: 'Taskade AI',
    url: 'https://taskade.com',
    category: 'productivity',
    description: 'AI task management & collaboration',
    icon: '✅',
    color: '#6366f1',
    freeType: 'freemium',
    tags: ['productivity', 'tasks', 'AI', 'team', 'notes'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'prod-005',
    name: 'Beautiful.ai',
    url: 'https://beautiful.ai',
    category: 'productivity',
    description: 'AI-powered presentations - free trial',
    icon: '✨',
    color: '#ec4899',
    freeType: 'limited',
    tags: ['productivity', 'presentation', 'design', 'AI'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'prod-006',
    name: 'Durable',
    url: 'https://durable.co',
    category: 'productivity',
    description: 'AI website builder in 30 seconds - free',
    icon: '🌐',
    color: '#10b981',
    freeType: 'limited',
    tags: ['productivity', 'website', 'builder', 'AI', 'fast'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // 👤 AI AVATAR & FACE
  // ─────────────────────────────────────────────
  {
    id: 'avatar-001',
    name: 'HeyGen',
    url: 'https://heygen.com',
    category: 'avatar',
    description: 'AI video avatars - 1 free video/month',
    icon: '🎭',
    color: '#7c3aed',
    freeType: 'limited',
    tags: ['avatar', 'video', 'face', 'presenter', 'heygen'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'avatar-002',
    name: 'D-ID',
    url: 'https://d-id.com',
    category: 'avatar',
    description: 'Talking photo AI - free credits',
    icon: '🗣️',
    color: '#2563eb',
    freeType: 'credits',
    tags: ['avatar', 'talking', 'photo', 'AI', 'video'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'avatar-003',
    name: 'Fotor AI',
    url: 'https://fotor.com/ai-photo-editor',
    category: 'avatar',
    description: 'AI photo editing & avatar - free plan',
    icon: '📸',
    color: '#f97316',
    freeType: 'limited',
    tags: ['avatar', 'photo', 'edit', 'face', 'AI'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'avatar-004',
    name: 'Reface AI',
    url: 'https://reface.ai',
    category: 'avatar',
    description: 'Face swap and avatar creation',
    icon: '🔄',
    color: '#ec4899',
    freeType: 'freemium',
    tags: ['avatar', 'face', 'swap', 'fun', 'AI'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // 🎨 AI IMAGE — EXTRA TOOLS
  // ─────────────────────────────────────────────
  {
    id: 'img-011',
    name: 'Craiyon',
    url: 'https://craiyon.com',
    category: 'image',
    description: 'Completely free AI image generator, no signup',
    icon: '🖌️',
    color: '#f97316',
    freeType: 'free',
    tags: ['image', 'generate', 'free', 'no signup', 'craiyon'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'img-012',
    name: 'NightCafe',
    url: 'https://creator.nightcafe.studio',
    category: 'image',
    description: 'AI art generator - free daily credits',
    icon: '🌙',
    color: '#1e1b4b',
    freeType: 'credits',
    tags: ['image', 'art', 'generate', 'nightcafe', 'daily'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'img-013',
    name: 'Artbreeder',
    url: 'https://artbreeder.com',
    category: 'image',
    description: 'Blend and create AI portraits & landscapes',
    icon: '🧬',
    color: '#7c3aed',
    freeType: 'freemium',
    tags: ['image', 'blend', 'portrait', 'landscape', 'artbreeder'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'img-014',
    name: 'Deep Dream Generator',
    url: 'https://deepdreamgenerator.com',
    category: 'image',
    description: 'AI dream-style image transformation',
    icon: '🌀',
    color: '#4f46e5',
    freeType: 'freemium',
    tags: ['image', 'dream', 'style', 'transform', 'deep'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'img-015',
    name: 'Pixlr AI',
    url: 'https://pixlr.com/ai-image-generator',
    category: 'image',
    description: 'Free online AI photo editor + generator',
    icon: '🖼️',
    color: '#0ea5e9',
    freeType: 'freemium',
    tags: ['image', 'edit', 'generate', 'pixlr', 'photo'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'img-016',
    name: 'Fotor AI Generator',
    url: 'https://fotor.com/ai-image-generator',
    category: 'image',
    description: 'AI image generation - free plan available',
    icon: '📷',
    color: '#f59e0b',
    freeType: 'limited',
    tags: ['image', 'generate', 'fotor', 'free'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'img-017',
    name: 'Stable Diffusion Web',
    url: 'https://stablediffusionweb.com',
    category: 'image',
    description: 'Run Stable Diffusion free in browser',
    icon: '⚡',
    color: '#8b5cf6',
    freeType: 'free',
    tags: ['image', 'stable diffusion', 'browser', 'free', 'generate'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'img-018',
    name: 'Lexica',
    url: 'https://lexica.art',
    category: 'image',
    description: 'Stable Diffusion search + generation - free',
    icon: '📖',
    color: '#6366f1',
    freeType: 'freemium',
    tags: ['image', 'search', 'generate', 'stable diffusion', 'lexica'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'img-019',
    name: 'Photosonic',
    url: 'https://writesonic.com/photosonic',
    category: 'image',
    description: 'AI image generator - free credits',
    icon: '🌅',
    color: '#f97316',
    freeType: 'credits',
    tags: ['image', 'generate', 'photosonic', 'writesonic'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'img-020',
    name: 'Picsart AI',
    url: 'https://picsart.com/create',
    category: 'image',
    description: 'AI photo editing and generation suite',
    icon: '🎭',
    color: '#ec4899',
    freeType: 'freemium',
    tags: ['image', 'edit', 'generate', 'picsart', 'collage'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'img-021',
    name: 'Runway Gen-3',
    url: 'https://runwayml.com',
    category: 'image',
    description: 'Professional AI image & video editing',
    icon: '🎬',
    color: '#18181b',
    freeType: 'credits',
    tags: ['image', 'video', 'edit', 'runway', 'professional'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'img-022',
    name: 'Krea AI',
    url: 'https://krea.ai',
    category: 'image',
    description: 'Real-time AI image generation - free',
    icon: '🔴',
    color: '#ef4444',
    freeType: 'freemium',
    tags: ['image', 'realtime', 'generate', 'krea', 'live'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'img-023',
    name: 'Tensor.art',
    url: 'https://tensor.art',
    category: 'image',
    description: 'Free AI image models community platform',
    icon: '🧠',
    color: '#7c3aed',
    freeType: 'free',
    tags: ['image', 'models', 'community', 'tensor', 'free'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'img-024',
    name: 'Getimg.ai',
    url: 'https://getimg.ai',
    category: 'image',
    description: 'AI image toolkit - generate, edit, expand',
    icon: '🖼️',
    color: '#10b981',
    freeType: 'credits',
    tags: ['image', 'generate', 'edit', 'expand', 'toolkit'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // 🎬 AI VIDEO — EXTRA TOOLS
  // ─────────────────────────────────────────────
  {
    id: 'vid-007',
    name: 'Stable Video',
    url: 'https://stability.ai/stable-video',
    category: 'video',
    description: 'Stability AI video generation - free credits',
    icon: '📹',
    color: '#7c3aed',
    freeType: 'credits',
    tags: ['video', 'generate', 'stability', 'stable', 'AI'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'vid-008',
    name: 'Viggle AI',
    url: 'https://viggle.ai',
    category: 'video',
    description: 'Animate any character with motion - free',
    icon: '🕺',
    color: '#f97316',
    freeType: 'free',
    tags: ['video', 'animate', 'character', 'motion', 'viggle'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'vid-009',
    name: 'Haiper AI',
    url: 'https://haiper.ai',
    category: 'video',
    description: 'AI video generation platform - free tier',
    icon: '🌊',
    color: '#3b82f6',
    freeType: 'limited',
    tags: ['video', 'generate', 'haiper', 'AI'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'vid-010',
    name: 'Invideo AI',
    url: 'https://invideo.io',
    category: 'video',
    description: 'AI video from script/text - free plan',
    icon: '🎥',
    color: '#8b5cf6',
    freeType: 'freemium',
    tags: ['video', 'script', 'text', 'invideo', 'youtube'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'vid-011',
    name: 'Pictory',
    url: 'https://pictory.ai',
    category: 'video',
    description: 'Convert articles to videos with AI',
    icon: '📰',
    color: '#ec4899',
    freeType: 'limited',
    tags: ['video', 'article', 'convert', 'pictory', 'content'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'vid-012',
    name: 'Synthesia',
    url: 'https://synthesia.io',
    category: 'video',
    description: 'AI avatar presenter videos - free demo',
    icon: '🧑‍💼',
    color: '#6366f1',
    freeType: 'limited',
    tags: ['video', 'avatar', 'presenter', 'synthesia', 'AI'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'vid-013',
    name: 'Mootion',
    url: 'https://mootion.com',
    category: 'video',
    description: 'AI 3D motion video generation',
    icon: '💃',
    color: '#f43f5e',
    freeType: 'credits',
    tags: ['video', '3d', 'motion', 'animate', 'mootion'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'vid-014',
    name: 'Veed.io AI',
    url: 'https://veed.io',
    category: 'video',
    description: 'AI video editor with subtitles - free plan',
    icon: '✂️',
    color: '#10b981',
    freeType: 'freemium',
    tags: ['video', 'edit', 'subtitle', 'veed', 'auto-caption'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // 💬 AI CHAT — EXTRA TOOLS
  // ─────────────────────────────────────────────
  {
    id: 'chat-008',
    name: 'Groq',
    url: 'https://groq.com',
    category: 'chat',
    description: 'Fastest free AI inference - Llama, Mixtral',
    icon: '⚡',
    color: '#f97316',
    freeType: 'free',
    tags: ['chat', 'groq', 'fast', 'llama', 'free'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'chat-009',
    name: 'HuggingChat',
    url: 'https://huggingface.co/chat',
    category: 'chat',
    description: 'Open source AI chat by HuggingFace - free',
    icon: '🤗',
    color: '#ff9d00',
    freeType: 'free',
    tags: ['chat', 'huggingface', 'open source', 'free', 'models'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'chat-010',
    name: 'Cohere',
    url: 'https://coral.cohere.com',
    category: 'chat',
    description: 'Command R - free AI chat + web search',
    icon: '🌊',
    color: '#39d353',
    freeType: 'free',
    tags: ['chat', 'cohere', 'command', 'search', 'free'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'chat-011',
    name: 'Pi AI',
    url: 'https://pi.ai',
    category: 'chat',
    description: 'Personal AI companion - free, conversational',
    icon: '🥧',
    color: '#6366f1',
    freeType: 'free',
    tags: ['chat', 'pi', 'companion', 'personal', 'inflection'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'chat-012',
    name: 'Poe',
    url: 'https://poe.com',
    category: 'chat',
    description: 'Access multiple AI models in one place - free',
    icon: '🎭',
    color: '#7c3aed',
    freeType: 'freemium',
    tags: ['chat', 'poe', 'multiple', 'models', 'quora'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'chat-013',
    name: 'Phind',
    url: 'https://phind.com',
    category: 'chat',
    description: 'AI search for developers - free',
    icon: '💡',
    color: '#3b82f6',
    freeType: 'free',
    tags: ['chat', 'search', 'developer', 'code', 'phind'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'chat-014',
    name: 'Komo AI',
    url: 'https://komo.ai',
    category: 'chat',
    description: 'Fast AI search engine - free',
    icon: '🔍',
    color: '#10b981',
    freeType: 'free',
    tags: ['chat', 'search', 'fast', 'komo', 'free'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // ✍️ AI WRITING — EXTRA TOOLS
  // ─────────────────────────────────────────────
  {
    id: 'write-006',
    name: 'Writesonic',
    url: 'https://writesonic.com',
    category: 'writing',
    description: 'AI writer for blogs, ads, emails - free plan',
    icon: '✍️',
    color: '#f97316',
    freeType: 'freemium',
    tags: ['writing', 'blog', 'ads', 'writesonic', 'SEO'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'write-007',
    name: 'Jasper AI',
    url: 'https://jasper.ai',
    category: 'writing',
    description: 'AI content writer - free trial',
    icon: '🤖',
    color: '#6366f1',
    freeType: 'limited',
    tags: ['writing', 'content', 'jasper', 'marketing', 'blog'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'write-008',
    name: 'Sudowrite',
    url: 'https://sudowrite.com',
    category: 'writing',
    description: 'AI creative writing assistant - free trial',
    icon: '📚',
    color: '#8b5cf6',
    freeType: 'limited',
    tags: ['writing', 'creative', 'fiction', 'story', 'novel'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'write-009',
    name: 'HemingwayApp',
    url: 'https://hemingwayapp.com',
    category: 'writing',
    description: 'Make writing bold and clear - free web version',
    icon: '✒️',
    color: '#f59e0b',
    freeType: 'free',
    tags: ['writing', 'edit', 'clarity', 'hemingway', 'readability'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'write-010',
    name: 'Hypotenuse AI',
    url: 'https://hypotenuse.ai',
    category: 'writing',
    description: 'AI product descriptions & content - free trial',
    icon: '📝',
    color: '#ec4899',
    freeType: 'limited',
    tags: ['writing', 'product', 'ecommerce', 'description', 'content'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'write-011',
    name: 'Wordtune',
    url: 'https://wordtune.com',
    category: 'writing',
    description: 'AI rewriting and summarizing - free plan',
    icon: '🎵',
    color: '#7c3aed',
    freeType: 'freemium',
    tags: ['writing', 'rewrite', 'summarize', 'wordtune', 'tone'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'write-012',
    name: 'AI Poem Generator',
    url: 'https://poem-generator.com',
    category: 'writing',
    description: 'Free AI poem and poetry generator',
    icon: '🌸',
    color: '#f43f5e',
    freeType: 'free',
    tags: ['writing', 'poem', 'poetry', 'creative', 'free'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // 💻 AI CODE — EXTRA TOOLS
  // ─────────────────────────────────────────────
  {
    id: 'code-007',
    name: 'Windsurf',
    url: 'https://codeium.com/windsurf',
    category: 'code',
    description: 'AI code editor by Codeium - free',
    icon: '🏄',
    color: '#06b6d4',
    freeType: 'free',
    tags: ['code', 'editor', 'windsurf', 'codeium', 'free'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'code-008',
    name: 'Codeium',
    url: 'https://codeium.com',
    category: 'code',
    description: 'Free AI code completion for any IDE',
    icon: '💚',
    color: '#10b981',
    freeType: 'free',
    tags: ['code', 'completion', 'IDE', 'codeium', 'free'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'code-009',
    name: 'Tabnine',
    url: 'https://tabnine.com',
    category: 'code',
    description: 'AI code completion - free basic plan',
    icon: '⌨️',
    color: '#6366f1',
    freeType: 'freemium',
    tags: ['code', 'completion', 'tabnine', 'autocomplete'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'code-010',
    name: 'Lovable',
    url: 'https://lovable.dev',
    category: 'code',
    description: 'AI full-stack app builder - free credits',
    icon: '❤️',
    color: '#f43f5e',
    freeType: 'credits',
    tags: ['code', 'fullstack', 'build', 'lovable', 'app'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'code-011',
    name: 'Blackbox AI',
    url: 'https://blackbox.ai',
    category: 'code',
    description: 'AI coding assistant - free',
    icon: '⬛',
    color: '#18181b',
    freeType: 'free',
    tags: ['code', 'assistant', 'blackbox', 'free', 'search'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'code-012',
    name: 'Pieces for Developers',
    url: 'https://pieces.app',
    category: 'code',
    description: 'AI code snippets manager - free',
    icon: '🧩',
    color: '#f97316',
    freeType: 'free',
    tags: ['code', 'snippets', 'save', 'pieces', 'developer'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'code-013',
    name: 'AI Code Reviewer',
    url: 'https://coderabbit.ai',
    category: 'code',
    description: 'AI code review for GitHub PRs - free for open source',
    icon: '🐇',
    color: '#f97316',
    freeType: 'limited',
    tags: ['code', 'review', 'github', 'PR', 'quality'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'code-014',
    name: 'StackBlitz AI',
    url: 'https://stackblitz.com',
    category: 'code',
    description: 'Online IDE with AI - free for public projects',
    icon: '⚡',
    color: '#1374ef',
    freeType: 'freemium',
    tags: ['code', 'IDE', 'online', 'stackblitz', 'react'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // 🎵 AI AUDIO — EXTRA TOOLS
  // ─────────────────────────────────────────────
  {
    id: 'audio-006',
    name: 'Soundraw',
    url: 'https://soundraw.io',
    category: 'audio',
    description: 'AI music generation for content - free plan',
    icon: '🎼',
    color: '#3b82f6',
    freeType: 'freemium',
    tags: ['audio', 'music', 'generate', 'soundraw', 'content'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'audio-007',
    name: 'Loudly',
    url: 'https://loudly.com',
    category: 'audio',
    description: 'AI music creation platform - free plan',
    icon: '🔊',
    color: '#ec4899',
    freeType: 'freemium',
    tags: ['audio', 'music', 'create', 'loudly', 'beats'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'audio-008',
    name: 'Voicemod',
    url: 'https://voicemod.net',
    category: 'audio',
    description: 'Real-time AI voice changer - free version',
    icon: '🎙️',
    color: '#7c3aed',
    freeType: 'freemium',
    tags: ['audio', 'voice', 'change', 'realtime', 'voicemod'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'audio-009',
    name: 'Descript',
    url: 'https://descript.com',
    category: 'audio',
    description: 'AI audio/video editing - free plan',
    icon: '✂️',
    color: '#6366f1',
    freeType: 'freemium',
    tags: ['audio', 'video', 'edit', 'transcript', 'descript'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'audio-010',
    name: 'Splash Music',
    url: 'https://splashmusic.com',
    category: 'audio',
    description: 'Free AI beat and music maker',
    icon: '💦',
    color: '#0ea5e9',
    freeType: 'free',
    tags: ['audio', 'music', 'beats', 'splash', 'free'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'audio-011',
    name: 'Eleven Dubbing',
    url: 'https://elevenlabs.io/dubbing',
    category: 'audio',
    description: 'AI video dubbing in any language - free credits',
    icon: '🌍',
    color: '#1a1a2e',
    freeType: 'credits',
    tags: ['audio', 'dubbing', 'translate', 'video', 'language'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'audio-012',
    name: 'Whisper (OpenAI)',
    url: 'https://huggingface.co/spaces/openai/whisper',
    category: 'audio',
    description: 'Free speech to text transcription - open source',
    icon: '🗣️',
    color: '#10a37f',
    freeType: 'free',
    tags: ['audio', 'transcribe', 'speech', 'text', 'whisper'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // 🎭 AI DESIGN — EXTRA TOOLS
  // ─────────────────────────────────────────────
  {
    id: 'design-006',
    name: 'Uizard',
    url: 'https://uizard.io',
    category: 'design',
    description: 'Sketch to UI design with AI - free plan',
    icon: '📱',
    color: '#7c3aed',
    freeType: 'freemium',
    tags: ['design', 'ui', 'sketch', 'wireframe', 'uizard'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'design-007',
    name: 'Framer AI',
    url: 'https://framer.com',
    category: 'design',
    description: 'AI website design - free plan',
    icon: '🖥️',
    color: '#0ea5e9',
    freeType: 'freemium',
    tags: ['design', 'website', 'framer', 'AI', 'prototype'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'design-008',
    name: 'Relume',
    url: 'https://relume.io',
    category: 'design',
    description: 'AI website sitemap and wireframe builder',
    icon: '🗺️',
    color: '#18181b',
    freeType: 'freemium',
    tags: ['design', 'sitemap', 'wireframe', 'relume', 'website'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'design-009',
    name: 'Khroma',
    url: 'https://khroma.co',
    category: 'design',
    description: 'AI color tool that learns your preferences - free',
    icon: '🎨',
    color: '#f43f5e',
    freeType: 'free',
    tags: ['design', 'color', 'palette', 'learn', 'khroma'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'design-010',
    name: 'Mockup AI',
    url: 'https://mockupai.com',
    category: 'design',
    description: 'AI product mockup generator - free plan',
    icon: '📦',
    color: '#f59e0b',
    freeType: 'limited',
    tags: ['design', 'mockup', 'product', 'presentation'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'design-011',
    name: 'Autodraw',
    url: 'https://autodraw.com',
    category: 'design',
    description: 'Google AI drawing assistant - completely free',
    icon: '✏️',
    color: '#4285f4',
    freeType: 'free',
    tags: ['design', 'draw', 'sketch', 'google', 'free'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'design-012',
    name: 'Magician (Figma)',
    url: 'https://magician.design',
    category: 'design',
    description: 'AI magic inside Figma - design automation',
    icon: '🪄',
    color: '#f24e1e',
    freeType: 'freemium',
    tags: ['design', 'figma', 'plugin', 'magic', 'automation'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // 🧊 AI 3D — EXTRA TOOLS
  // ─────────────────────────────────────────────
  {
    id: '3d-004',
    name: 'Sloyd',
    url: 'https://sloyd.ai',
    category: '3d',
    description: 'AI 3D game asset generator - free tier',
    icon: '🎮',
    color: '#f97316',
    freeType: 'freemium',
    tags: ['3d', 'game', 'asset', 'sloyd', 'generate'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: '3d-005',
    name: 'CSM.ai',
    url: 'https://csm.ai',
    category: '3d',
    description: 'Image to 3D model - free credits',
    icon: '📸',
    color: '#6366f1',
    freeType: 'credits',
    tags: ['3d', 'image', 'model', 'csm', 'generate'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: '3d-006',
    name: 'Tripo3D',
    url: 'https://tripo3d.ai',
    category: '3d',
    description: 'Fast text/image to 3D - free daily credits',
    icon: '⚡',
    color: '#10b981',
    freeType: 'credits',
    tags: ['3d', 'text', 'image', 'tripo', 'fast'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: '3d-007',
    name: 'Blockade Labs',
    url: 'https://skybox.blockadelabs.com',
    category: '3d',
    description: 'AI 360° skybox and environment generation',
    icon: '🌐',
    color: '#7c3aed',
    freeType: 'freemium',
    tags: ['3d', 'skybox', '360', 'environment', 'vr'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // 🔍 AI SEARCH — EXTRA TOOLS
  // ─────────────────────────────────────────────
  {
    id: 'search-004',
    name: 'Brave Search AI',
    url: 'https://search.brave.com',
    category: 'search',
    description: 'Privacy-focused AI search engine - free',
    icon: '🦁',
    color: '#f97316',
    freeType: 'free',
    tags: ['search', 'brave', 'privacy', 'AI', 'free'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'search-005',
    name: 'Elicit',
    url: 'https://elicit.com',
    category: 'search',
    description: 'AI research assistant for papers - free',
    icon: '🔬',
    color: '#6366f1',
    freeType: 'freemium',
    tags: ['search', 'research', 'papers', 'elicit', 'academic'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'search-006',
    name: 'Scite.ai',
    url: 'https://scite.ai',
    category: 'search',
    description: 'AI citation analysis - free plan',
    icon: '📊',
    color: '#0ea5e9',
    freeType: 'freemium',
    tags: ['search', 'citation', 'papers', 'scite', 'research'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'search-007',
    name: 'SciSpace',
    url: 'https://scispace.com',
    category: 'search',
    description: 'AI research paper reader - free',
    icon: '🚀',
    color: '#7c3aed',
    freeType: 'freemium',
    tags: ['search', 'papers', 'read', 'explain', 'scispace'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // ⚡ PRODUCTIVITY — EXTRA TOOLS
  // ─────────────────────────────────────────────
  {
    id: 'prod-007',
    name: 'Tome',
    url: 'https://tome.app',
    category: 'productivity',
    description: 'AI storytelling and presentation tool - free',
    icon: '📖',
    color: '#7c3aed',
    freeType: 'freemium',
    tags: ['productivity', 'presentation', 'story', 'tome', 'AI'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'prod-008',
    name: 'Notion AI',
    url: 'https://notion.so',
    category: 'productivity',
    description: 'AI workspace - notes, docs, wikis',
    icon: '📝',
    color: '#000000',
    freeType: 'freemium',
    tags: ['productivity', 'notes', 'docs', 'notion', 'wiki'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'prod-009',
    name: 'Tldraw AI',
    url: 'https://tldraw.com',
    category: 'productivity',
    description: 'Free infinite canvas with AI drawing',
    icon: '🎨',
    color: '#f43f5e',
    freeType: 'free',
    tags: ['productivity', 'canvas', 'draw', 'whiteboard', 'free'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'prod-010',
    name: 'Xmind AI',
    url: 'https://xmind.ai',
    category: 'productivity',
    description: 'AI mind mapping - free basic plan',
    icon: '🧠',
    color: '#f97316',
    freeType: 'freemium',
    tags: ['productivity', 'mindmap', 'brainstorm', 'xmind'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'prod-011',
    name: 'Miro AI',
    url: 'https://miro.com',
    category: 'productivity',
    description: 'AI-powered visual collaboration - free plan',
    icon: '🖼️',
    color: '#f9d71c',
    freeType: 'freemium',
    tags: ['productivity', 'whiteboard', 'collaboration', 'miro'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'prod-012',
    name: 'Fireflies.ai',
    url: 'https://fireflies.ai',
    category: 'productivity',
    description: 'AI meeting recorder + summarizer - free plan',
    icon: '🦋',
    color: '#7c3aed',
    freeType: 'freemium',
    tags: ['productivity', 'meeting', 'record', 'summarize', 'transcript'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'prod-013',
    name: 'Magical AI',
    url: 'https://magical.so',
    category: 'productivity',
    description: 'AI text expander for Chrome - free',
    icon: '⚡',
    color: '#6366f1',
    freeType: 'free',
    tags: ['productivity', 'text', 'expand', 'chrome', 'shortcut'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'prod-014',
    name: 'Reclaim AI',
    url: 'https://reclaim.ai',
    category: 'productivity',
    description: 'AI calendar scheduling - free plan',
    icon: '📅',
    color: '#10b981',
    freeType: 'freemium',
    tags: ['productivity', 'calendar', 'schedule', 'reclaim', 'time'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'prod-015',
    name: 'Summarize.tech',
    url: 'https://summarize.tech',
    category: 'productivity',
    description: 'Summarize YouTube videos with AI - free',
    icon: '▶️',
    color: '#ff0000',
    freeType: 'free',
    tags: ['productivity', 'youtube', 'summarize', 'video', 'free'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'prod-016',
    name: 'Consensus AI',
    url: 'https://consensus.app',
    category: 'productivity',
    description: 'AI research from 200M papers - free plan',
    icon: '📚',
    color: '#059669',
    freeType: 'freemium',
    tags: ['productivity', 'research', 'papers', 'science', 'consensus'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // 👤 AI AVATAR — EXTRA TOOLS
  // ─────────────────────────────────────────────
  {
    id: 'avatar-005',
    name: 'Character AI',
    url: 'https://character.ai',
    category: 'avatar',
    description: 'Chat with AI characters - free',
    icon: '🎭',
    color: '#7c3aed',
    freeType: 'free',
    tags: ['avatar', 'character', 'chat', 'roleplay', 'AI'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'avatar-006',
    name: 'Lensa AI',
    url: 'https://prisma-ai.com/lensa',
    category: 'avatar',
    description: 'AI magic avatar photo editing app',
    icon: '✨',
    color: '#f43f5e',
    freeType: 'freemium',
    tags: ['avatar', 'photo', 'magic', 'lensa', 'portrait'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'avatar-007',
    name: 'Picso',
    url: 'https://picso.ai',
    category: 'avatar',
    description: 'AI avatar maker from selfie - free credits',
    icon: '🤳',
    color: '#ec4899',
    freeType: 'credits',
    tags: ['avatar', 'selfie', 'ai art', 'portrait', 'picso'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // 🌐 AI WEBSITE BUILDERS
  // ─────────────────────────────────────────────
  {
    id: 'web-001',
    name: 'Wix AI',
    url: 'https://wix.com/ai-website-builder',
    category: 'productivity',
    description: 'AI website builder - free plan',
    icon: '🌐',
    color: '#0c6efc',
    freeType: 'freemium',
    tags: ['website', 'builder', 'wix', 'AI', 'free'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'web-002',
    name: 'Sitekick AI',
    url: 'https://sitekick.ai',
    category: 'productivity',
    description: 'AI landing page builder in seconds',
    icon: '🚀',
    color: '#7c3aed',
    freeType: 'freemium',
    tags: ['website', 'landing page', 'builder', 'sitekick', 'AI'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'web-003',
    name: 'Webflow AI',
    url: 'https://webflow.com',
    category: 'productivity',
    description: 'Visual web builder with AI - free plan',
    icon: '🌊',
    color: '#4353ff',
    freeType: 'freemium',
    tags: ['website', 'webflow', 'design', 'no-code', 'AI'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // 📊 AI DATA & ANALYTICS
  // ─────────────────────────────────────────────
  {
    id: 'data-001',
    name: 'Julius AI',
    url: 'https://julius.ai',
    category: 'productivity',
    description: 'Chat with your data & CSV files - free plan',
    icon: '📊',
    color: '#3b82f6',
    freeType: 'freemium',
    tags: ['data', 'csv', 'analytics', 'julius', 'charts'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'data-002',
    name: 'Obviously AI',
    url: 'https://obviously.ai',
    category: 'productivity',
    description: 'No-code AI predictions from data - free trial',
    icon: '🔮',
    color: '#7c3aed',
    freeType: 'limited',
    tags: ['data', 'predict', 'ml', 'no-code', 'analytics'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'data-003',
    name: 'Rows AI',
    url: 'https://rows.com',
    category: 'productivity',
    description: 'AI spreadsheet with data analysis - free plan',
    icon: '📈',
    color: '#10b981',
    freeType: 'freemium',
    tags: ['data', 'spreadsheet', 'rows', 'AI', 'analytics'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // 🎓 AI EDUCATION & LEARNING
  // ─────────────────────────────────────────────
  {
    id: 'edu-001',
    name: 'Khan Academy AI',
    url: 'https://khanmigo.ai',
    category: 'chat',
    description: 'Free AI tutor by Khan Academy',
    icon: '🎓',
    color: '#14a800',
    freeType: 'free',
    tags: ['education', 'tutor', 'learn', 'khan', 'free'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'edu-002',
    name: 'Explainpaper',
    url: 'https://explainpaper.com',
    category: 'search',
    description: 'AI explains research papers simply - free',
    icon: '📄',
    color: '#3b82f6',
    freeType: 'free',
    tags: ['education', 'papers', 'explain', 'research', 'AI'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'edu-003',
    name: 'Quizlet AI',
    url: 'https://quizlet.com',
    category: 'productivity',
    description: 'AI flashcards and study tools - free',
    icon: '🃏',
    color: '#4255ff',
    freeType: 'freemium',
    tags: ['education', 'flashcards', 'study', 'quizlet', 'learn'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // 🤖 AI AUTOMATION
  // ─────────────────────────────────────────────
  {
    id: 'auto-001',
    name: 'Make (Integromat)',
    url: 'https://make.com',
    category: 'productivity',
    description: 'Visual AI automation platform - free plan',
    icon: '⚙️',
    color: '#6d00cc',
    freeType: 'freemium',
    tags: ['automation', 'workflow', 'make', 'integromat', 'connect'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'auto-002',
    name: 'n8n',
    url: 'https://n8n.io',
    category: 'productivity',
    description: 'Open source AI workflow automation - free self-host',
    icon: '🔄',
    color: '#ff6d5a',
    freeType: 'free',
    tags: ['automation', 'workflow', 'n8n', 'open source', 'self-host'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'auto-003',
    name: 'Zapier AI',
    url: 'https://zapier.com',
    category: 'productivity',
    description: 'AI app automation - free plan (100 tasks/month)',
    icon: '⚡',
    color: '#ff4a00',
    freeType: 'limited',
    tags: ['automation', 'zapier', 'connect', 'workflow', 'apps'],
    isActive: true,
    addedAt: '2026-01-01',
  },

  // ─────────────────────────────────────────────
  // 🌟 BONUS: TRENDING / VIRAL AI TOOLS
  // ─────────────────────────────────────────────
  {
    id: 'trend-001',
    name: 'Grok',
    url: 'https://grok.com',
    category: 'chat',
    description: 'xAI Grok - real-time AI with X/Twitter data',
    icon: '🤖',
    color: '#18181b',
    freeType: 'freemium',
    tags: ['chat', 'grok', 'xai', 'twitter', 'realtime'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'trend-002',
    name: 'DeepSeek',
    url: 'https://chat.deepseek.com',
    category: 'chat',
    description: 'DeepSeek R1 - powerful reasoning AI - free',
    icon: '🐋',
    color: '#1e40af',
    freeType: 'free',
    tags: ['chat', 'deepseek', 'reasoning', 'free', 'R1'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'trend-003',
    name: 'Sora (OpenAI)',
    url: 'https://sora.com',
    category: 'video',
    description: 'OpenAI Sora - cinematic AI video generation',
    icon: '🎬',
    color: '#10a37f',
    freeType: 'limited',
    tags: ['video', 'sora', 'openai', 'cinematic', 'generate'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'trend-004',
    name: 'Dia Browser',
    url: 'https://diabrowser.com',
    category: 'productivity',
    description: 'AI-first web browser - free',
    icon: '🌐',
    color: '#7c3aed',
    freeType: 'free',
    tags: ['browser', 'AI', 'dia', 'productivity', 'web'],
    isActive: true,
    addedAt: '2026-01-01',
  },
  {
    id: 'trend-005',
    name: 'Manus AI',
    url: 'https://manus.ai',
    category: 'productivity',
    description: 'Autonomous AI agent for complex tasks',
    icon: '🤖',
    color: '#f97316',
    freeType: 'limited',
    tags: ['agent', 'autonomous', 'manus', 'tasks', 'AI'],
    isActive: true,
    addedAt: '2026-01-01',
  },
];

// ─────────────────────────────────────────────
// HELPER FUNCTIONS
// ─────────────────────────────────────────────

export function getLinksByCategory(category: string): AILink[] {
  if (category === 'all') return JARVIS_LINKS.filter(l => l.isActive);
  return JARVIS_LINKS.filter(l => l.category === category && l.isActive);
}

export function searchLinks(query: string): AILink[] {
  const q = query.toLowerCase();
  return JARVIS_LINKS.filter(l =>
    l.isActive &&
    (
      l.name.toLowerCase().includes(q) ||
      l.description.toLowerCase().includes(q) ||
      l.tags.some(t => t.toLowerCase().includes(q)) ||
      l.category.toLowerCase().includes(q)
    )
  );
}

export function getLinkById(id: string): AILink | undefined {
  return JARVIS_LINKS.find(l => l.id === id);
}

export const TOTAL_LINKS = JARVIS_LINKS.length;
